// code\tools\parse-modules\parser\module-parser.cpp generated by reflex 5.5.0 from code\tools\parse-modules\parser\module-parser.l

#define REFLEX_VERSION "5.5.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_fast
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_nodefault
#undef REFLEX_OPTION_noline
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_unicode

#define REFLEX_OPTION_fast                true
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           Soup::ParseModules
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_noline              true
#define REFLEX_OPTION_outfile             "code\\tools\\parse-modules\\parser\\module-parser.cpp"
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


module;

# include <iostream>
# include <chrono>
# include <optional>
# include <unordered_map>
# include <vector>

export module parse.modules:ModuleParser;
import reflex;
import :EarlyExitException;

enum class SimplifiedCppToken : int
{
    EndOfFile = 0,
    Identifier,
    Period,
    Colon,
    Semicolon,
    Module,
    Import,
    Export,
};



////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/matcher.h>
#endif

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/abslexer.h>
#endif

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace Soup {
namespace ParseModules {

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual int lex(void);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

} // namespace Soup
} // namespace ParseModules

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace Soup {
namespace ParseModules {
extern void reflex_code_INITIAL(reflex::Matcher&);
} // namespace Soup
} // namespace ParseModules

int Soup::ParseModules::Lexer::lex(void)
{
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              lexer_error("scanner jammed");
              return int();
            }
            break;
          case 1: // rule code\tools\parse-modules\parser\module-parser.l:39: {whitespace} :
{ /* ignore whitespace */ }
            break;
          case 2: // rule code\tools\parse-modules\parser\module-parser.l:40: {preprocessor} :
{ /* ignore preprocessor statements */ }
            break;
          case 3: // rule code\tools\parse-modules\parser\module-parser.l:41: {comment} :
{ /* ignore comments */ }
            break;
          case 4: // rule code\tools\parse-modules\parser\module-parser.l:42: {multiline_comment} :
{ /* ignore comments */ }
            break;
          case 5: // rule code\tools\parse-modules\parser\module-parser.l:43: {newline} :
{ /* ignore newlines */ }
            break;
          case 6: // rule code\tools\parse-modules\parser\module-parser.l:44: "import" :
return (int)SimplifiedCppToken::Import;
            break;
          case 7: // rule code\tools\parse-modules\parser\module-parser.l:45: "export" :
return (int)SimplifiedCppToken::Export;
            break;
          case 8: // rule code\tools\parse-modules\parser\module-parser.l:46: "module" :
return (int)SimplifiedCppToken::Module;
            break;
          case 9: // rule code\tools\parse-modules\parser\module-parser.l:47: "." :
return (int)SimplifiedCppToken::Period;
            break;
          case 10: // rule code\tools\parse-modules\parser\module-parser.l:48: ":" :
return (int)SimplifiedCppToken::Colon;
            break;
          case 11: // rule code\tools\parse-modules\parser\module-parser.l:49: ";" :
return (int)SimplifiedCppToken::Semicolon;
            break;
          case 12: // rule code\tools\parse-modules\parser\module-parser.l:50: {identifier} :
return (int)SimplifiedCppToken::Identifier;
            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


namespace Soup::ParseModules
{

/// <summary>
/// Gradient decent Module parser
/// </summary>
export class ModuleParser : public Lexer
{
private:
    SimplifiedCppToken _currentToken;
    SimplifiedCppToken _nextToken;
    std::vector<std::string> _result;

public:
    ModuleParser(const reflex::Input& input) :
        Lexer(input),
        _currentToken(),
        _nextToken((SimplifiedCppToken)-1),
        _result()
    {
    }

    bool TryParse()
    {
        MoveNext();

        // Check if there is an optional global module declaration
        if (TryParseOptionalGlobalModuleFragment())
        {
            // TODO: Parse global module fragment

            // Must have a module declaration
            bool isExport;
            std::string moduleName;
            if (!TryParseModuleDeclaration(isExport, moduleName))
                throw std::runtime_error("TU with global module fragment must have a module declaration");

            if (isExport)
                _result.push_back("module-interface " + moduleName);
            else
                _result.push_back("module-implementation " + moduleName);
        }
        else
        {
            // Check for optional module declarationn
            bool isExport;
            std::string moduleName;
            if (TryParseModuleDeclaration(isExport, moduleName))
            {
                if (isExport)
                    _result.push_back("module-interface " + moduleName);
                else
                    _result.push_back("module-implementation " + moduleName);
            }
        }

        std::string importName;
        while (TryParseImportModule(importName))
        {
            _result.push_back("import " + importName);
        }

        return true;
    }

    std::vector<std::string> GetResult()
    {
      return std::move(_result);
    }

private:
    bool TryParseOptionalGlobalModuleFragment()
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseOptionalGlobalModuleFragment" << std::endl;
        #endif

        // Verify first token is module
        if (_currentToken == SimplifiedCppToken::Module &&
          PeekNext() == SimplifiedCppToken::Semicolon)
        {
            // Move past the semicolon
            MoveNext();
            MoveNext();

            // There is a global module fragment
            return true;
        }

        return false;
    }

    bool TryParseModuleDeclaration(bool& isExport, std::string& moduleName)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModuleDeclaration" << std::endl;
        #endif

        // Check for optional first export token
        bool hasExport = _currentToken == SimplifiedCppToken::Export;
        if (hasExport)
        {
            MoveNext();
        }

        // Verify required module token
        if (_currentToken != SimplifiedCppToken::Module)
        {
            // Only return false here since there is not tokens that indicate a module declaration
            return false;
        }

        MoveNext();

        std::string result;
        if (!TryParseModuleName(result))
            throw std::runtime_error("Malformed module name in module declaration");

        // Check for optional partition
        std::string partitionName;
        if (TryParseModulePartition(partitionName))
        {
            result += partitionName;
        }

        // Verify semicolon after module name
        if (_currentToken != SimplifiedCppToken::Semicolon)
            throw std::runtime_error("Malformed module declaration");

        MoveNext();

        isExport = hasExport;
        moduleName = std::move(result);
        return true;
    }

    bool TryParseModuleName(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModuleName" << std::endl;
        #endif

        auto result = std::string();

        // Verify first token is an identifier
        if (_currentToken == SimplifiedCppToken::Identifier)
            result += str();
        else
            return false;

        // Check for optional period separators
        MoveNext();
        while (_currentToken == SimplifiedCppToken::Period)
        {
            result += str();

            // Verify required identifier
            MoveNext();
            if (_currentToken == SimplifiedCppToken::Identifier)
                result += str();
            else
                return false;

            MoveNext();
        }

        name = std::move(result);
        return true;
    }

    bool TryParseModulePartition(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModulePartition" << std::endl;
        #endif

        // Verify first token is a colon
        if (_currentToken != SimplifiedCppToken::Colon)
            return false;

        MoveNext();
        auto moduleName = std::string();
        if (!TryParseModuleName(moduleName))
          return false;

        auto result = std::string(":");
        result += moduleName;
        name = std::move(result);
        return true;
    }

    bool TryParseHeaderName(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseHeaderName" << std::endl;
        #endif

        // TODO: Implement header imports
        name = "TODO";
        return false;
    }

    bool TryParseImportModule(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseImportModule" << std::endl;
        #endif

        // Check for optional first export and required import
        if (_currentToken == SimplifiedCppToken::Import)
        {
        }
        else if (_currentToken == SimplifiedCppToken::Export && PeekNext() == SimplifiedCppToken::Import)
        {
            // Has Export
            MoveNext();
        }
        else
        {
          return false;
        }

        MoveNext();

        auto result = std::string();
        if (TryParseModuleName(result))
        {
            name = std::move(result);
        }
        else if (TryParseModulePartition(result))
        {
            name = std::move(result);
        }
        else if (TryParseHeaderName(result))
        {
            name = std::move(result);
        }
        else
        {
            return false;
        }

        // Verify semicolon at end
        if (_currentToken != SimplifiedCppToken::Semicolon)
            return false;

        MoveNext();

        return true;
    }

    /// Lexer exceptions.
    virtual void lexer_error(const char* message = nullptr) override
    {
        // If jammed then treat it as the end of the file
        if (message == std::string_view("scanner jammed"))
        {
            #ifdef SHOW_TOKENS
            std::cout << "Scanner jammed" << '\n';
            #endif
        }
        else
        {
            std::stringstream stream_message;
            stream_message << (message != NULL ? message : "lexer error") << " at " << lineno() << ":" << columno();
            throw EarlyExitException(stream_message.str());
        }
    }

    SimplifiedCppToken PeekNext()
    {
        if (_nextToken == (SimplifiedCppToken)-1)
        {
            _nextToken = (SimplifiedCppToken)lex();
        }

        return _nextToken;
    }

    SimplifiedCppToken MoveNext()
    {
        if (_nextToken != (SimplifiedCppToken)-1)
        {
            _currentToken = _nextToken;
            _nextToken = (SimplifiedCppToken)-1;
        }
        else
        {
            _currentToken = (SimplifiedCppToken)lex();
        }

        #ifdef SHOW_TOKENS
        switch (_currentToken)
        {
            case SimplifiedCppToken::EndOfFile:
                std::cout << "Token: " << "EndOfFile" << '\n';
                break;
            case SimplifiedCppToken::Module:
                std::cout << "Token: " << "Module" << '\n';
                break;
            case SimplifiedCppToken::Export:
                std::cout << "Token: " << "Export" << '\n';
                break;
            case SimplifiedCppToken::Import:
                std::cout << "Token: " << "Import" << '\n';
                break;
            case SimplifiedCppToken::Colon:
                std::cout << "Token: " << "Colon" << '\n';
                break;
            case SimplifiedCppToken::Semicolon:
                std::cout << "Token: " << "Semicolon" << '\n';
                break;
            case SimplifiedCppToken::Period:
                std::cout << "Token: " << "Period" << '\n';
                break;
            case SimplifiedCppToken::Identifier:
                std::cout << "Token: " << "Identifier" << '\n';
                break;
            default:
                std::cout << "Token: " << "UNKNOWN" << '\n';
                break;
        }
        #endif

        return _currentToken;
    }
};

}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  TABLES                                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/matcher.h>
#endif

#if defined(OS_WIN)
#pragma warning(disable:4101 4102)
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#elif defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-label"
#endif

namespace Soup {
namespace ParseModules {

void reflex_code_INITIAL(reflex::Matcher& m)
{
  int c = 0;
  m.FSM_INIT(c);

// S0:
  m.FSM_FIND();
  c = m.FSM_CHAR();
  if (c == 'm') goto S44;
  if (c == 'i') goto S30;
  if (c == 'e') goto S37;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if (c == ';') goto S55;
  if (c == ':') goto S53;
  if (c == '/') goto S23;
  if (c == '.') goto S51;
  if (c == '#') goto S20;
  if (c == ' ') goto S16;
  if (c == '\r') goto S26;
  if (c == '\n') goto S28;
  if (c == '\t') goto S16;
  return m.FSM_HALT(c);

S16:
  m.FSM_TAKE(1);
  c = m.FSM_CHAR();
  if (c == ' ') goto S16;
  if (c == '\t') goto S16;
  return m.FSM_HALT(c);

S20:
  c = m.FSM_CHAR();
  if (c == '\r') goto S63;
  if (c == '\n') goto S65;
  if (0 <= c) goto S67;
  return m.FSM_HALT(c);

S23:
  c = m.FSM_CHAR();
  if (c == '/') goto S69;
  if (c == '*') goto S72;
  return m.FSM_HALT(c);

S26:
  c = m.FSM_CHAR();
  if (c == '\n') goto S28;
  return m.FSM_HALT(c);

S28:
  m.FSM_TAKE(5);
  return m.FSM_HALT();

S30:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'm') goto S83;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S37:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'x') goto S90;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S44:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'o') goto S97;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S51:
  m.FSM_TAKE(9);
  return m.FSM_HALT();

S53:
  m.FSM_TAKE(10);
  return m.FSM_HALT();

S55:
  m.FSM_TAKE(11);
  return m.FSM_HALT();

S57:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S63:
  c = m.FSM_CHAR();
  if (c == '\n') goto S65;
  if (0 <= c) goto S67;
  return m.FSM_HALT(c);

S65:
  m.FSM_TAKE(2);
  return m.FSM_HALT();

S67:
  c = m.FSM_CHAR();
  if (c == '\n') goto S65;
  if (0 <= c) goto S67;
  return m.FSM_HALT(c);

S69:
  c = m.FSM_CHAR();
  if (c == '\r') goto S104;
  if (c == '\n') goto S106;
  if (0 <= c) goto S108;
  return m.FSM_HALT(c);

S72:
  c = m.FSM_CHAR();
  if (c == 244) goto S124;
  if (241 <= c && c <= 243) goto S122;
  if (c == 240) goto S120;
  if (238 <= c && c <= 239) goto S118;
  if (c == 237) goto S116;
  if (225 <= c && c <= 236) goto S114;
  if (c == 224) goto S112;
  if (194 <= c && c <= 223) goto S110;
  if (128 <= c) return m.FSM_HALT(c);
  if (c == '*') goto S126;
  if (0 <= c && c <= 127) goto S72;
  return m.FSM_HALT(c);

S83:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'p') goto S138;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S90:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'p') goto S145;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S97:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'd') goto S152;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S104:
  c = m.FSM_CHAR();
  if (c == '\n') goto S106;
  if (0 <= c) goto S108;
  return m.FSM_HALT(c);

S106:
  m.FSM_TAKE(3);
  return m.FSM_HALT();

S108:
  c = m.FSM_CHAR();
  if (c == '\n') goto S106;
  if (0 <= c) goto S108;
  return m.FSM_HALT(c);

S110:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S72;
  return m.FSM_HALT(c);

S112:
  c = m.FSM_CHAR();
  if (160 <= c && c <= 191) goto S159;
  return m.FSM_HALT(c);

S114:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S161;
  return m.FSM_HALT(c);

S116:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 159) goto S163;
  return m.FSM_HALT(c);

S118:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S165;
  return m.FSM_HALT(c);

S120:
  c = m.FSM_CHAR();
  if (144 <= c && c <= 191) goto S167;
  return m.FSM_HALT(c);

S122:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S169;
  return m.FSM_HALT(c);

S124:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 143) goto S171;
  return m.FSM_HALT(c);

S126:
  c = m.FSM_CHAR();
  if (c == 244) goto S198;
  if (241 <= c && c <= 243) goto S196;
  if (c == 240) goto S194;
  if (238 <= c && c <= 239) goto S192;
  if (c == 237) goto S190;
  if (225 <= c && c <= 236) goto S188;
  if (c == 224) goto S186;
  if (194 <= c && c <= 223) goto S184;
  if (128 <= c) return m.FSM_HALT(c);
  if (c == '/') goto S200;
  if (c == '*') goto S126;
  if (0 <= c && c <= 127) goto S173;
  return m.FSM_HALT(c);

S138:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'o') goto S202;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S145:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'o') goto S209;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S152:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'u') goto S216;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S159:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S72;
  return m.FSM_HALT(c);

S161:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S72;
  return m.FSM_HALT(c);

S163:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S72;
  return m.FSM_HALT(c);

S165:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S72;
  return m.FSM_HALT(c);

S167:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S223;
  return m.FSM_HALT(c);

S169:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S225;
  return m.FSM_HALT(c);

S171:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S227;
  return m.FSM_HALT(c);

S173:
  c = m.FSM_CHAR();
  if (c == 244) goto S243;
  if (241 <= c && c <= 243) goto S241;
  if (c == 240) goto S239;
  if (238 <= c && c <= 239) goto S237;
  if (c == 237) goto S235;
  if (225 <= c && c <= 236) goto S233;
  if (c == 224) goto S231;
  if (194 <= c && c <= 223) goto S229;
  if (128 <= c) return m.FSM_HALT(c);
  if (c == '*') goto S245;
  if (0 <= c && c <= 127) goto S173;
  return m.FSM_HALT(c);

S184:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S186:
  c = m.FSM_CHAR();
  if (160 <= c && c <= 191) goto S257;
  return m.FSM_HALT(c);

S188:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S259;
  return m.FSM_HALT(c);

S190:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 159) goto S261;
  return m.FSM_HALT(c);

S192:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S263;
  return m.FSM_HALT(c);

S194:
  c = m.FSM_CHAR();
  if (144 <= c && c <= 191) goto S265;
  return m.FSM_HALT(c);

S196:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S267;
  return m.FSM_HALT(c);

S198:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 143) goto S269;
  return m.FSM_HALT(c);

S200:
  m.FSM_TAKE(4);
  return m.FSM_HALT();

S202:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'r') goto S271;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S209:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'r') goto S278;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S216:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'l') goto S285;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S223:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S72;
  return m.FSM_HALT(c);

S225:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S72;
  return m.FSM_HALT(c);

S227:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S72;
  return m.FSM_HALT(c);

S229:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S231:
  c = m.FSM_CHAR();
  if (160 <= c && c <= 191) goto S292;
  return m.FSM_HALT(c);

S233:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S294;
  return m.FSM_HALT(c);

S235:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 159) goto S296;
  return m.FSM_HALT(c);

S237:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S298;
  return m.FSM_HALT(c);

S239:
  c = m.FSM_CHAR();
  if (144 <= c && c <= 191) goto S300;
  return m.FSM_HALT(c);

S241:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S302;
  return m.FSM_HALT(c);

S243:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 143) goto S304;
  return m.FSM_HALT(c);

S245:
  c = m.FSM_CHAR();
  if (c == 244) goto S198;
  if (241 <= c && c <= 243) goto S196;
  if (c == 240) goto S194;
  if (238 <= c && c <= 239) goto S192;
  if (c == 237) goto S190;
  if (225 <= c && c <= 236) goto S188;
  if (c == 224) goto S186;
  if (194 <= c && c <= 223) goto S184;
  if (128 <= c) return m.FSM_HALT(c);
  if (c == '/') goto S200;
  if (c == '*') goto S245;
  if (0 <= c && c <= 127) goto S173;
  return m.FSM_HALT(c);

S257:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S259:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S261:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S263:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S265:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S306;
  return m.FSM_HALT(c);

S267:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S308;
  return m.FSM_HALT(c);

S269:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S310;
  return m.FSM_HALT(c);

S271:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 't') goto S312;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S278:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 't') goto S318;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S285:
  m.FSM_TAKE(12);
  c = m.FSM_CHAR();
  if (c == 'e') goto S324;
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S292:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S294:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S296:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S298:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S300:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S330;
  return m.FSM_HALT(c);

S302:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S332;
  return m.FSM_HALT(c);

S304:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S334;
  return m.FSM_HALT(c);

S306:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S308:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S310:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S312:
  m.FSM_TAKE(6);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S318:
  m.FSM_TAKE(7);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S324:
  m.FSM_TAKE(8);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S57;
  if (c == '_') goto S57;
  if ('A' <= c && c <= 'Z') goto S57;
  if ('1' <= c && c <= '9') goto S57;
  return m.FSM_HALT(c);

S330:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S332:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);

S334:
  c = m.FSM_CHAR();
  if (128 <= c && c <= 191) goto S173;
  return m.FSM_HALT(c);
}

} // namespace Soup

} // namespace ParseModules

